  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_account_status {

  public enum AccountStatus has copy, drop , store {
                                Blocked,Frozen,Liquid
                        }

  public fun new_blocked(): AccountStatus {
    AccountStatus::Blocked
  }

  public fun new_frozen(): AccountStatus {
    AccountStatus::Frozen
  }

  public fun new_liquid(): AccountStatus {
    AccountStatus::Liquid
  }
}
