  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_asset_created_event {

  use sui::event;

  use std::ascii::String;

  use dubhe::dubhe_account_status::AccountStatus;

  use dubhe::dubhe_asset_status::AssetStatus;

  use dubhe::dubhe_asset_type::AssetType;

  use dubhe::dubhe_account::Account;

  use dubhe::dubhe_asset_metadata::AssetMetadata;

  use dubhe::dubhe_pool::Pool;

  use dubhe::dubhe_path_element::PathElement;

  use dubhe::dubhe_bridge_config::BridgeConfig;

  use dubhe::dubhe_dapp_metadata::DappMetadata;

  use dubhe::dubhe_dapp_stats::DappStats;

  public struct AssetCreatedEvent has copy, drop {
    asset_id: u256,
    name: String,
    symbol: String,
    owner: address,
    is_mintable: bool,
    is_burnable: bool,
    is_freezable: bool,
  }

  public fun new(
    asset_id: u256,
    name: String,
    symbol: String,
    owner: address,
    is_mintable: bool,
    is_burnable: bool,
    is_freezable: bool,
  ): AssetCreatedEvent {
    AssetCreatedEvent {
                                   asset_id,name,symbol,owner,is_mintable,is_burnable,is_freezable
                               }
  }
}
