  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_asset_wrapped_event {

  use sui::event;

  use std::ascii::String;

  use dubhe::dubhe_account_status::AccountStatus;

  use dubhe::dubhe_asset_status::AssetStatus;

  use dubhe::dubhe_asset_type::AssetType;

  use dubhe::dubhe_account::Account;

  use dubhe::dubhe_asset_metadata::AssetMetadata;

  use dubhe::dubhe_pool::Pool;

  use dubhe::dubhe_path_element::PathElement;

  use dubhe::dubhe_bridge_config::BridgeConfig;

  use dubhe::dubhe_dapp_metadata::DappMetadata;

  use dubhe::dubhe_dapp_stats::DappStats;

  public struct AssetWrappedEvent has copy, drop {
    from: address,
    asset_id: u256,
    amount: u256,
    beneficiary: address,
  }

  public fun new(from: address, asset_id: u256, amount: u256, beneficiary: address): AssetWrappedEvent {
    AssetWrappedEvent {
                                   from,asset_id,amount,beneficiary
                               }
  }
}
