  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_asset_status {

  public enum AssetStatus has copy, drop , store {
                                Frozen,Liquid
                        }

  public fun new_frozen(): AssetStatus {
    AssetStatus::Frozen
  }

  public fun new_liquid(): AssetStatus {
    AssetStatus::Liquid
  }
}
