  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_dapp_stats {

  use std::ascii::String;

  public struct DappStats has copy, drop, store {
    remaining_set_count: u256,
    per_set_fee: u256,
    total_set_count: u256,
    total_set_fees_paid: u256,
  }

  public fun new(
    remaining_set_count: u256,
    per_set_fee: u256,
    total_set_count: u256,
    total_set_fees_paid: u256,
  ): DappStats {
    DappStats {
                                   remaining_set_count,per_set_fee,total_set_count,total_set_fees_paid
                               }
  }

  public fun get(self: &DappStats): (u256,u256,u256,u256) {
    (self.remaining_set_count,self.per_set_fee,self.total_set_count,self.total_set_fees_paid)
  }

  public fun get_remaining_set_count(self: &DappStats): u256 {
    self.remaining_set_count
  }

  public fun get_per_set_fee(self: &DappStats): u256 {
    self.per_set_fee
  }

  public fun get_total_set_count(self: &DappStats): u256 {
    self.total_set_count
  }

  public fun get_total_set_fees_paid(self: &DappStats): u256 {
    self.total_set_fees_paid
  }

  public(package) fun set_remaining_set_count(self: &mut DappStats, remaining_set_count: u256) {
    self.remaining_set_count = remaining_set_count;
  }

  public(package) fun set_per_set_fee(self: &mut DappStats, per_set_fee: u256) {
    self.per_set_fee = per_set_fee;
  }

  public(package) fun set_total_set_count(self: &mut DappStats, total_set_count: u256) {
    self.total_set_count = total_set_count;
  }

  public(package) fun set_total_set_fees_paid(self: &mut DappStats, total_set_fees_paid: u256) {
    self.total_set_fees_paid = total_set_fees_paid;
  }

  public(package) fun set(
    self: &mut DappStats,
    remaining_set_count: u256,
    per_set_fee: u256,
    total_set_count: u256,
    total_set_fees_paid: u256,
  ) {
    self.remaining_set_count = remaining_set_count;
    self.per_set_fee = per_set_fee;
    self.total_set_count = total_set_count;
    self.total_set_fees_paid = total_set_fees_paid;
  }
}
