  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_liquidity_added_event {

  use sui::event;

  use std::ascii::String;

  use dubhe::dubhe_account_status::AccountStatus;

  use dubhe::dubhe_asset_status::AssetStatus;

  use dubhe::dubhe_asset_type::AssetType;

  use dubhe::dubhe_account::Account;

  use dubhe::dubhe_asset_metadata::AssetMetadata;

  use dubhe::dubhe_pool::Pool;

  use dubhe::dubhe_path_element::PathElement;

  use dubhe::dubhe_bridge_config::BridgeConfig;

  use dubhe::dubhe_dapp_metadata::DappMetadata;

  use dubhe::dubhe_dapp_stats::DappStats;

  public struct LiquidityAddedEvent has copy, drop {
    who: address,
    asset1_id: u256,
    asset2_id: u256,
    asset1_amount: u256,
    asset2_amount: u256,
    lp_asset_id: u256,
    lp_asset_minted: u256,
  }

  public fun new(
    who: address,
    asset1_id: u256,
    asset2_id: u256,
    asset1_amount: u256,
    asset2_amount: u256,
    lp_asset_id: u256,
    lp_asset_minted: u256,
  ): LiquidityAddedEvent {
    LiquidityAddedEvent {
                                   who,asset1_id,asset2_id,asset1_amount,asset2_amount,lp_asset_id,lp_asset_minted
                               }
  }
}
