  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_path_element {

  use std::ascii::String;

  public struct PathElement has copy, drop, store {
    asset_id: u256,
    balance: u256,
  }

  public fun new(asset_id: u256, balance: u256): PathElement {
    PathElement {
                                   asset_id,balance
                               }
  }

  public fun get(self: &PathElement): (u256,u256) {
    (self.asset_id,self.balance)
  }

  public fun get_asset_id(self: &PathElement): u256 {
    self.asset_id
  }

  public fun get_balance(self: &PathElement): u256 {
    self.balance
  }

  public(package) fun set_asset_id(self: &mut PathElement, asset_id: u256) {
    self.asset_id = asset_id;
  }

  public(package) fun set_balance(self: &mut PathElement, balance: u256) {
    self.balance = balance;
  }

  public(package) fun set(self: &mut PathElement, asset_id: u256, balance: u256) {
    self.asset_id = asset_id;
    self.balance = balance;
  }
}
