  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_pool {

  use std::ascii::String;

  public struct Pool has copy, drop, store {
    pool_address: address,
    lp_asset_id: u256,
  }

  public fun new(pool_address: address, lp_asset_id: u256): Pool {
    Pool {
                                   pool_address,lp_asset_id
                               }
  }

  public fun get(self: &Pool): (address,u256) {
    (self.pool_address,self.lp_asset_id)
  }

  public fun get_pool_address(self: &Pool): address {
    self.pool_address
  }

  public fun get_lp_asset_id(self: &Pool): u256 {
    self.lp_asset_id
  }

  public(package) fun set_pool_address(self: &mut Pool, pool_address: address) {
    self.pool_address = pool_address;
  }

  public(package) fun set_lp_asset_id(self: &mut Pool, lp_asset_id: u256) {
    self.lp_asset_id = lp_asset_id;
  }

  public(package) fun set(self: &mut Pool, pool_address: address, lp_asset_id: u256) {
    self.pool_address = pool_address;
    self.lp_asset_id = lp_asset_id;
  }
}
