  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::deploy_hook {
  use dubhe::dapp_service::DappHub;
  use dubhe::dapp_fee_config;
  use std::ascii::{string, String};
  use dubhe::dapp_key;
  use dubhe::dapp_key::DappKey;

  public(package) fun run(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    // set free credit
    let free_credit = 10 * 1000000000;
    let base_fee = 80000;
    let byte_fee = 500;
    dapp_fee_config::set(dapp_hub, free_credit, base_fee, byte_fee, ctx);
  }
}
