  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dms::dms_errors {

  #[error]

  const INVALID_CONTENT_LENGTH: vector<u8> = b"Content length must be less than 12";

  public fun invalid_content_length_error(condition: bool) {
    assert!(condition, INVALID_CONTENT_LENGTH)
  }
}
