  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dms::dms_events {

  use std::ascii::{String, string};

  use dms::dms_message_sent_event::MessageSentEvent;

  use dms::dms_message_sent_event;

  public fun message_sent_event(sender: address, content: String) {
    dubhe::storage_event::emit_set_record<MessageSentEvent, MessageSentEvent, MessageSentEvent>(
				string(b"message_sent_event"),
				option::none(),
			  	option::none(),
			  option::some(dms_message_sent_event::new(sender,content))
			  )
  }
}
