  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dms::dms_schema {

  use std::ascii::String;

  use std::ascii::string;

  use sui::package::UpgradeCap;

  use std::type_name;

  use dubhe::storage;

  use dubhe::storage_value::{Self, StorageValue};

  use dubhe::storage_map::{Self, StorageMap};

  use dubhe::storage_double_map::{Self, StorageDoubleMap};

  use sui::dynamic_field as df;

  public struct Schema has key, store {
    id: UID,
  }

  public fun borrow_message(self: &Schema): &StorageValue<String> {
    storage::borrow_field(&self.id, b"message")
  }

  public(package) fun message(self: &mut Schema): &mut StorageValue<String> {
    storage::borrow_mut_field(&mut self.id, b"message")
  }

  public(package) fun create(ctx: &mut TxContext): Schema {
    let mut id = object::new(ctx);
    storage::add_field<StorageValue<String>>(&mut id, b"message", storage_value::new(b"message", ctx));
    Schema { id }
  }

  public(package) fun id(self: &mut Schema): &mut UID {
    &mut self.id
  }

  public(package) fun borrow_id(self: &Schema): &UID {
    &self.id
  }

  public fun migrate(_schema: &mut Schema, _cap: &UpgradeCap, _ctx: &mut TxContext) {}

  // ======================================== View Functions ========================================

  public fun get_message(self: &Schema): &String {
    self.borrow_message().get()
  }

  // =========================================================================================================
}
