  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dms::dms_deploy_hook {
    use std::ascii::string;
    use dms::dms_schema::Schema;

  public(package) fun run(_schema: &mut Schema, _ctx: &mut TxContext) {
    _schema.message().set(string(b"Hello World!"));
  }
}
